name: Draft Release

on:
  push:
    tags:
      - 'v*' # Matches tags starting with "v"

jobs:
  update-draft-release:
    - name: Dump job github var
      env:
        GITHUB_VAR: ${{ toJson(github) }}
      run: echo "$GITHUB_VAR"