name: Draft Release

on:
  push:
    tags:
      - 'v*' # Matches tags starting with "v"

jobs:
  update-draft-release:
    if: ${{ github.ref_name == 'main' && !startsWith(github.event.head_commit.message, '[no-release-draft]') }}
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
