name: Draft Release

on:
  push:
    tags:
      - 'v*' # Matches tags starting with "v"

jobs:
  update-draft-release:
    runs-on: ubuntu-latest # Specify the runner
    steps:
      - name: Dump job github var
        env:
          GITHUB_VAR: ${{ toJson(github) }}
        run: echo "$GITHUB_VAR"
